Run go fmt on git actions testing

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,6 +21,15 @@ jobs:
       - name: Compiles
         run: go build ./...
 
+      - name: Runs go fmt
+        if: ${{ success() }}
+        run: |
+          OUTPUT=$(go fmt ./... 2>&1)
+          if [ ! -z "$OUTPUT" ]; then
+            echo "go fmt failed on the following files:"
+            echo "$OUTPUT"
+            exit 1
+          fi
       - name: Runs unit tests
         if: ${{ success() }}
         run: go test -coverprofile ./unitcoverage.out ./...
