SOL-117089: updated git actions checks for go version 1.22, go vet and staticcheck
Signed-off-by: Chris Morgan <17009318+cjwmorgan-sol@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -42,7 +42,7 @@ jobs:
       - name: Setup Go environment
         uses: actions/setup-go@v2.1.3
         with:
-          go-version: '1.21'
+          go-version: '1.22'
           check-latest: true
       - name: Check Go Version
         run: go version
@@ -66,6 +66,28 @@ jobs:
             echo "$OUTPUT"
             exit 1
           fi
+
+      - name: Runs go vet
+        if: ${{ success() }}
+        run: |
+          OUTPUT=$(go vet ./... 2>&1)
+          if [ ! -z "$OUTPUT" ]; then
+            echo "go vet failed on the following:"
+            echo "$OUTPUT"
+            exit 1
+          fi
+
+      - name: Runs staticcheck
+        if: ${{ success() }}
+        run: |
+          go install honnef.co/go/tools/cmd/staticcheck@v0.3.3
+          OUTPUT=$(staticcheck --checks=all ./...)
+          if [ ! -z "$OUTPUT" ]; then
+            echo "staticcheck failed on the following:"
+            echo "$OUTPUT"
+            exit 1
+          fi
+
       - name: Runs unit tests
         if: ${{ success() }}
         run: go test -coverprofile ./unitcoverage.out ./...
